/**
 * Phase 0 — sync the two Preprod wallets.
 *
 * This is the long pole of the whole Wave 1 plan and nothing else removes it:
 * each wallet takes ~2h to sync from genesis, and DUST (which pays fees) then
 * *accrues over time* from held NIGHT rather than being purchased. So both
 * wallets need funding on day 1 even though neither is used until later.
 *
 *   deployer — shielded; deploys the audit-anchor contract and calls circuits
 *   agent    — unshielded; the Intents signing demo
 *
 * Seeds are generated on first run and written to .env.local (gitignored) so
 * addresses stay stable across restarts. Losing that file means re-syncing from
 * scratch, so it is deliberately not regenerated when present.
 *
 *   npm run sync-wallets            # sync both, report, exit when synced
 *   npm run sync-wallets -- --watch # stay attached and keep reporting
 */
import { randomBytes } from "node:crypto";
import { readFileSync, writeFileSync, existsSync, appendFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { WalletBuilder } from "@midnight-ntwrk/wallet";
import { NetworkId } from "@midnight-ntwrk/zswap";
import { unshieldedAddressForSeed } from "./unshielded-address.js";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const ENV_LOCAL = resolve(ROOT, ".env.local");

const WATCH = process.argv.includes("--watch");

let envLoaded = false;
function loadEnvLocal(): void {
  if (envLoaded) return;
  envLoaded = true;
  if (!existsSync(ENV_LOCAL)) return;
  for (const line of readFileSync(ENV_LOCAL, "utf8").split("\n")) {
    const m = /^([A-Z0-9_]+)=(.*)$/.exec(line.trim());
    if (m && !process.env[m[1]]) process.env[m[1]] = m[2];
  }
}

function env(key: string, fallback: string): string {
  loadEnvLocal();
  const v = process.env[key];
  return v && v.trim() ? v.trim() : fallback;
}

// Preprod. Overridable, but these are the published endpoints.
const CFG = {
  indexer: env("MIDNIGHT_INDEXER_URL", "https://indexer.preprod.midnight.network/api/v4/graphql"),
  indexerWs: env("MIDNIGHT_INDEXER_WS_URL", "wss://indexer.preprod.midnight.network/api/v4/graphql/ws"),
  node: env("MIDNIGHT_NODE_URL", "https://rpc.preprod.midnight.network"),
  // Only needed to *prove* a transaction. Syncing does not touch it, so a
  // stopped proof server is fine for this script.
  proofServer: env("MIDNIGHT_PROOF_SERVER_URL", "http://127.0.0.1:6300"),
};

// Preprod runs under the TestNet network id.
const NETWORK_ID = NetworkId.TestNet;

/** Read a seed from env, or mint and persist one. Never regenerates. */
function seedFor(name: "DEPLOYER" | "AGENT"): string {
  loadEnvLocal();
  const key = `MIDNIGHT_${name}_SEED`;
  const existing = process.env[key];
  if (existing && /^[0-9a-f]{64}$/i.test(existing.trim())) return existing.trim().toLowerCase();

  const seed = randomBytes(32).toString("hex");
  if (!existsSync(ENV_LOCAL)) writeFileSync(ENV_LOCAL, "# Generated by sync-wallets-preprod. Gitignored. Back this up.\n");
  appendFileSync(ENV_LOCAL, `${key}=${seed}\n`);
  process.env[key] = seed;
  console.log(`  ! minted a new ${name} seed → .env.local (back this file up)`);
  return seed;
}

/**
 * The wallet-api package ships no types.d.ts at this version, so the state shape
 * is read defensively.
 *
 * Observed on Preprod: `syncProgress` stays `undefined` and coins/balances stay
 * empty for a wallet that has never been funded — there is simply no history to
 * catch up on. So "no progress" here does not mean stuck; it means unfunded.
 * The real gate is the faucet, and the ~2h catch-up only applies once the
 * wallet has chain activity to replay.
 */
function describe(state: Record<string, unknown>): {
  address?: string;
  funded: boolean;
  summary: string;
} {
  const address = state.address as string | undefined;
  const coins = (state.coins as unknown[] | undefined)?.length ?? 0;
  const pending = (state.pendingCoins as unknown[] | undefined)?.length ?? 0;
  const balances = (state.balances ?? {}) as Record<string, unknown>;
  const entries = Object.entries(balances);
  const funded = coins > 0 || pending > 0 || entries.length > 0;

  const sp = state.syncProgress as Record<string, unknown> | undefined;
  const progress = sp
    ? `sync ${JSON.stringify(sp)}`
    : "no chain history yet (unfunded)";

  const bal = entries.length
    ? entries.map(([k, v]) => `${k.slice(0, 10)}…=${String(v)}`).join(" ")
    : "none";

  return {
    address,
    funded,
    summary: `${progress} | coins=${coins} pending=${pending} | balances: ${bal}`,
  };
}

async function watchWallet(label: string, seed: string): Promise<void> {
  const wallet = await WalletBuilder.build(
    CFG.indexer,
    CFG.indexerWs,
    CFG.proofServer,
    CFG.node,
    seed,
    NETWORK_ID,
    "warn",
  );
  wallet.start();

  let lastLine = "";
  let announced = false;

  await new Promise<void>((done) => {
    const sub = wallet.state().subscribe((raw: unknown) => {
      const state = raw as Record<string, unknown>;
      const { address, funded, summary } = describe(state);

      // Print the address on the first emission: it is the thing the operator
      // needs in order to unblock everything else, and it is available long
      // before any funding arrives.
      if (!announced && address) {
        announced = true;
        // Both are printed because they are not interchangeable: the faucet
        // rejects the shielded one, and only the shielded one appears in
        // WalletState. Handing over just `address` is what sends people to the
        // faucet with an address it will refuse.
        console.log(`[${label}] shielded   (wallet):  ${address}`);
        try {
          console.log(`[${label}] unshielded (faucet): ${unshieldedAddressForSeed(seed)}`);
        } catch (e) {
          console.log(`[${label}] unshielded derivation failed: ${(e as Error).message}`);
        }
      }

      const line = `[${label}] ${funded ? "FUNDED" : "waiting for funds"} | ${summary}`;
      if (line !== lastLine) {
        lastLine = line;
        console.log(`${new Date().toISOString().slice(11, 19)} ${line}`);
      }
      if (funded && !WATCH) {
        sub.unsubscribe();
        done();
      }
    });
  });

  await wallet.close();
}

async function main(): Promise<void> {
  console.log("Midnight Preprod wallets");
  console.log(`  indexer: ${CFG.indexer}`);
  console.log(`  node:    ${CFG.node}`);
  console.log(`  network: TestNet (${NETWORK_ID}) — Preprod`);
  console.log(
    "\n  A new wallet has no chain history, so it reports no sync progress until\n" +
      "  it is funded.\n\n" +
      "  Fund the UNSHIELDED (mn_addr_preprod1…) address of each wallet at\n" +
      "  https://faucet.preprod.midnight.network/ — the faucet rejects shielded\n" +
      "  addresses. Then register the NIGHT on-chain to start DUST accruing;\n" +
      "  holding NIGHT alone generates nothing, and DUST is what pays fees.\n",
  );

  // Watched concurrently: running them in sequence meant the second address was
  // never printed until the first was funded, which is exactly backwards — you
  // need both addresses up front in order to fund anything.
  await Promise.all([
    watchWallet("deployer", seedFor("DEPLOYER")),
    watchWallet("agent", seedFor("AGENT")),
  ]);

  console.log("\nBoth wallets funded.");
}

main().catch((e) => {
  console.error("sync failed:", e?.message ?? e);
  process.exit(1);
});
